import re
import spacy
from collections import defaultdict

# Load pre-trained NLP model (e.g., SpaCy or transformers)
nlp = spacy.load("en_core_web_sm")

# Define function to extract IoCs
def extract_iocs(text):
    iocs = defaultdict(list)
    
    # IP address extraction using regex
    ip_pattern = r"\b(?:[0-9]{1,3}\.){3}[0-9]{1,3}\b"
    iocs['IP addresses'] = re.findall(ip_pattern, text)
    
    # Domain extraction using regex
    domain_pattern = r"\b(?:[a-zA-Z0-9-]+\.)+[a-zA-Z]{2,6}\b"
    iocs['Domains'] = re.findall(domain_pattern, text)
    
    # Email extraction using regex
    email_pattern = r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"
    iocs['Emails'] = re.findall(email_pattern, text)
    
    return iocs

# Define function to extract TTPs
def extract_ttps(text):
    tactics = []
    techniques = []
    
    # Example Tactics from MITRE ATT&CK (expand this list)
    tactics_mapping = {
    "Reconnaissance": "TA0043",
    "Resource Development": "TA0042",
    "Initial Access": "TA0001",
    "Execution": "TA0002",
    "Persistence": "TA0003",
    "Privilege Escalation": "TA0004",
    "Defense Evasion": "TA0005",
    "Credential Access": "TA0006",
    "Discovery": "TA0007",
    "Lateral Movement": "TA0008",
    "Collection": "TA0009",
    "Command and Control": "TA0011",
    "Exfiltration": "TA0010",
    "Impact": "TA0040",
    "Network Effects": "TA0038",
    "Remote Service Effects": "TA0039",
    "Inhibit Response Function": "TA0107",
    "Impair Process Control": "TA0106",
    "Execution ": "TA0041",
    "Persistence ": "TA0028",
    "Privilege Escalation ": "TA0029",
    "Defense Evasion ": "TA0030",
    "Credential Access ": "TA0031",
    "Discovery ": "TA0032",
    "Lateral Movement ": "TA0033",
    "Collection ": "TA0035",
    "Command and Control ": "TA0037",
    "Exfiltration ": "TA0036",
    "Impact ": "TA0034",
    "Initial Access ": "TA0027",
    "Initial Access ": "TA0108",
    "Execution ": "TA0104",
    "Persistence ": "TA0110",
    "Privilege Escalation ": "TA0111",
    "Evasion": "TA0103",
    "Discovery ": "TA0102",
    "Lateral Movement ": "TA0109",
    "Collection ": "TA0100",
    "Command and Control ": "TA0101",
    "Impact ": "TA0105"
}
    
    techniques_mapping = {
    "Active Scanning": "T1595",
    "Scanning IP Blocks": "T1595.001",
    "Vulnerability Scanning": "T1595.002",
    "Wordlist Scanning": "T1595.003",
    "Gather Victim Host Information": "T1592",
    "Hardware": "T1592.001",
    "Software": "T1592.002",
    "Firmware": "T1592.003",
    "Client Configurations": "T1592.004",
    "Gather Victim Identity Information": "T1589",
    "Credentials": "T1589.001",
    "Email Addresses": "T1589.002",
    "Employee Names": "T1589.003",
    "Gather Victim Network Information": "T1590",
    "Domain Properties": "T1590.001",
    "DNS": "T1590.002",
    "Network Trust Dependencies": "T1590.003",
    "Network Topology": "T1590.004",
    "IP Addresses": "T1590.005",
    "Network Security Appliances": "T1590.006",
    "Gather Victim Org Information": "T1591",
    "Determine Physical Locations": "T1591.001",
    "Business Relationships": "T1591.002",
    "Identify Business Tempo": "T1591.003",
    "Identify Roles": "T1591.004",
    "Phishing for Information": "T1598",
    "Spearphishing Service": "T1598.001",
    "Spearphishing Attachment": "T1598.002",
    "Spearphishing Link": "T1598.003",
    "Spearphishing Voice": "T1598.004",
    "Search Closed Sources": "T1597",
    "Threat Intel Vendors": "T1597.001",
    "Purchase Technical Data": "T1597.002",
    "Search Open Technical Databases": "T1596",
    "DNS/Passive DNS": "T1596.001",
    "WHOIS": "T1596.002",
    "Digital Certificates": "T1596.003",
    "CDNs": "T1596.004",
    "Scan Databases": "T1596.005",
    "Search Open Websites/Domains": "T1593",
    "Social Media": "T1593.001",
    "Search Engines": "T1593.002",
    "Code Repositories": "T1593.003",
    "Search Victim-Owned Websites": "T1594",
    "Acquire Access": "T1650",
    "Acquire Infrastructure": "T1583",
    "Domains": "T1583.001",
    "DNS Server": "T1583.002",
    "Virtual Private Server": "T1583.003",
    "Server": "T1583.004",
    "Botnet": "T1583.005",
    "Web Services": "T1583.006",
    "Serverless": "T1583.007",
    "Malvertising": "T1583.008",
    "Compromise Accounts": "T1586",
    "Social Media Accounts": "T1586.001",
    "Email Accounts": "T1586.002",
    "Cloud Accounts": "T1586.003",
    "Acquire Access": "T1650",
    "Acquire Infrastructure": "T1583",
    "Domains": ".001",
    "DNS Server": ".002",
    "Virtual Private Server": ".003",
    "Server": ".004",
    "Botnet": ".005",
    "Web Services": ".006",
    "Serverless": ".007",
    "Malvertising": ".008",
    "Compromise Accounts": "T1586",
    "Social Media Accounts": ".001",
    "Email Accounts": ".002",
    "Cloud Accounts": ".003",
    "Obtain Capabilities": "T1588",
    "Malware": ".001",
    "Tool": ".002",
    "Code Signing Certificates": ".003",
    "Digital Certificates": ".004",
    "Exploits": ".005",
    "Vulnerabilities": ".006",
    "Artificial Intelligence": ".007",
    "Stage Capabilities": "T1608",
    "Upload Malware": ".001",
    "Upload Tool": ".002",
    "Install Digital Certificate": ".003",
    "Drive-by Target": ".004",
    "Link Target": ".005",
    "SEO Poisoning": ".006",
    "Content Injection": "T1659",
    "Drive-by Compromise": "T1189",
    "Exploit Public-Facing Application": "T1190",
    "External Remote Services": "T1133",
    "Hardware Additions": "T1200",
    "Phishing": "T1566",
    "Spearphishing Attachment": "T1566.001",
    "Spearphishing Link": "T1566.002",
    "Spearphishing via Service": "T1566.003",
    "Spearphishing Voice": "T1566.004",
    "Replication Through Removable Media": "T1091",
    "Supply Chain Compromise": "T1195",
    "Compromise Software Dependencies and Development Tools": "T1195.001",
    "Compromise Software Supply Chain": "T1195.002",
    "Compromise Hardware Supply Chain": "T1195.003",
    "Trusted Relationship": "T1199",
    "Valid Accounts": "T1078",
    "Default Accounts": "T1078.001",
    "Domain Accounts": "T1078.002",
    "Local Accounts": "T1078.003",
    "Cloud Accounts": "T1078.004",
    "Cloud Administration Command": "T1651",
    "Command and Scripting Interpreter": "T1059",
    "PowerShell": "T1059.001",
    "AppleScript": "T1059.002",
    "Windows Command Shell": "T1059.003",
    "Unix Shell": "T1059.004",
    "Visual Basic": "T1059.005",
    "Python": "T1059.006",
    "JavaScript": "T1059.007",
    "Network Device CLI": "T1059.008",
    "Cloud API": "T1059.009",
    "AutoHotKey & AutoIT": "T1059.010",
    "Lua": "T1059.011",
    "Container Administration Command": "T1609",
    "Deploy Container": "T1610",
    "Exploitation for Client Execution": "T1203",
    "Inter-Process Communication": "T1559",
    "Component Object Model": "T1559.001",
    "Dynamic Data Exchange": "T1559.002",
    "XPC Services": "T1559.003",
    "Native API": "T1106",
    "Scheduled Task/Job": "T1053",
    "At": "T1053.002",
    "Cron": "T1053.003",
    "Scheduled Task": "T1053.005",
    "Systemd Timers": "T1053.006",
    "Container Orchestration Job": "T1053.007",
    "Serverless Execution": "T1648",
    "Shared Modules": "T1129",
    "Software Deployment Tools": "T1072",
    "System Services": "T1569",
    "Launchctl": "T1569.001",
    "Service Execution": "T1569.002",
    "User Execution": "T1204",
    "Malicious Link": "T1204.001",
    "Malicious File": "T1204.002",
    "Malicious Image": "T1204.003",
    "Windows Management Instrumentation": "T1047"
}
    
    
    # Match tactics and techniques based on keywords
    for tactic, code in tactics_mapping.items():
        if tactic.lower() in text.lower():
            tactics.append([code, tactic])
    
    for technique, code in techniques_mapping.items():
        if technique.lower() in text.lower():
            techniques.append([code, technique])
    
    return {"Tactics": tactics, "Techniques": techniques}

# Define function to extract threat actors
def extract_threat_actors(text):
    threat_actors = []
    # Look for known threat actor names (expand this list)
    known_actors = ["admin@338",
    "Agrius",
    "Ajax Security Team",
    "Akira",
    "ALLANITE",
    "Andariel",
    "Aoqin Dragon",
    "APT-C-23",
    "APT-C-36",
    "APT1",
    "APT12",
    "APT16",
    "APT17",
    "APT18",
    "APT19",
    "APT28",
    "APT29",
    "APT3",
    "APT30",
    "APT32",
    "APT33",
    "APT37",
    "APT38",
    "APT39",
    "APT41",
    "APT5",
    "Aquatic Panda",
    "Axiom",
    "BackdoorDiplomacy",
    "BITTER",
    "BlackOasis",
    "BlackTech",
    "Blue Mockingbird",
    "Bouncing Golf",
    "BRONZE BUTLER",
    "Carbanak",
    "Chimera",
    "Cinnamon Tempest",
    "Cleaver",
    "Cobalt Group",
    "Confucius",
    "CopyKittens",
    "CURIUM",
    "CyberAv3ngers",
    "Daggerfly",
    "Dark Caracal",
    "Darkhotel",
    "DarkHydrus",
    "DarkVishnya",
    "Deep Panda",
    "Dragonfly",
    "DragonOK",
    "Earth Lusca",
    "Elderwood",
    "Ember Bear",
    "Equation",
    "Evilnum",
    "EXOTIC LILY",
    "Ferocious Kitten",
    "FIN10",
    "FIN13",
    "FIN4",
    "FIN5",
    "FIN6",
    "FIN7",
    "FIN8",
    "Fox Kitten",
    "GALLIUM",
    "Gallmaker",
    "Gamaredon Group",
    "GCMAN",
    "GOLD SOUTHFIELD",
    "Gorgon Group",
    "Group5",
    "HAFNIUM",
    "HEXANE",
    "Higaisa",
    "INC Ransom",
    "Inception",
    "IndigoZebra",
    "Indrik Spider",
    "Ke3chang",
    "Kimsuky",
    "LAPSUS$",
    "Lazarus Group",
    "LazyScripter",
    "Leafminer",
    "Leviathan",
    "Lotus Blossom",
    "LuminousMoth",
    "Machete",
    "Magic Hound",
    "Malteiro",
    "menuPass",
    "Metador",
    "Moafee",
    "Mofang",
    "Molerats",
    "Moonstone Sleet",
    "Moses Staff",
    "MoustachedBouncer",
    "MuddyWater",
    "Mustang Panda",
    "Mustard Tempest",
    "Naikon",
    "NEODYMIUM",
    "Nomadic Octopus",
    "OilRig",
    "Orangeworm",
    "Patchwork",
    "PittyTiger",
    "PLATINUM",
    "Play",
    "POLONIUM",
    "Poseidon Group",
    "PROMETHIUM",
    "Putter Panda",
    "Rancor",
    "RedCurl",
    "Rocke",
    "RTM",
    "Saint Bear",
    "Sandworm Team",
    "Scarlet Mimic",
    "Scattered Spider",
    "SideCopy",
    "Sidewinder",
    "Silence",
    "Silent Librarian",
    "SilverTerrier",
    "Sowbug",
    "Star Blizzard",
    "Stealth Falcon",
    "Strider",
    "Suckfly",
    "TA2541",
    "TA459",
    "TA505",
    "TA551",
    "TA577",
    "TA578",
    "TeamTNT",
    "TEMP.Veles",
    "The White Company",
    "Threat Group-1314",
    "Threat Group-3390",
    "Thrip",
    "ToddyCat",
    "Tonto Team",
    "Transparent Tribe",
    "Tropic Trooper",
    "Turla",
    "UNC788",
    "Volatile Cedar",
    "Volt Typhoon",
    "Whitefly",
    "Windigo",
    "Windshift",
    "Winnti Group",
    "Winter Vivern",
    "WIRTE",
    "Wizard Spider",
    "ZIRCONIUM"]
    for actor in known_actors:
        if actor.lower() in text.lower():
            threat_actors.append(actor)
    return threat_actors

# Define function to extract malware details
def extract_malware(text):
    malware_details = []
    # Look for known malware names (expand this list)
    known_malware = [ "3PARA RAT", "4H RAT", "AADInternals", "ABK", 
    "AbstractEmu", "ACAD/Medre.A", "AcidRain", "Action RAT", 
    "adbupd", "AdFind", "Adups", "ADVSTORESHELL", "Agent Smith", "Agent Tesla", "Agent.btz", "AhRat", 
    "Akira", "Allwinner", "Amadey", "Anchor", "Android/AdDisplay.Ashas", "Android/Chuli.A", 
    "AndroidOS/MalLocker.B", "ANDROIDOS_ANSERVER.A", "ANDROMEDA", "AndroRAT", "Anubis", "Apostle", 
    "AppleJeus", "AppleSeed", "Aria-body", "Arp", "Asacub", "ASPXSpy", "Astaroth", "AsyncRAT", "at", 
    "Attor", "AuditCred", "AuTo Stealer", "AutoIt backdoor", "Avaddon", "Avenger", "AvosLocker", "Azorult", 
    "Babuk", "BabyShark", "BackConfig", "Backdoor.Oldrea", "BACKSPACE", "Bad Rabbit", "BADCALL", 
    "BADFLICK", "BADHATCH", "BADNEWS", "BadPatch", "Bandook", "Bankshot", "Bazar", "BBK", "BBSRAT", 
    "BendyBear", "BFG Agonizer", "BISCUIT", "Bisonal", "BitPaymer", "BITSAdmin", "Black Basta", 
    "BlackCat", "BLACKCOFFEE", "BlackEnergy", "BlackMould", "BLINDINGCAN", "BloodHound", "BLUELIGHT", 
    "Bonadan", "BONDUPDATER", "BoomBox", "BOOSTWRITE", "BOOTRASH", "BOULDSPY", "BoxCaon", "BPFDoor", 
    "BrainTest", "BRATA", "Brave Prince", "Bread", "Briba", "Brute Ratel C4", "BS2005", "BUBBLEWRAP", 
    "build_downer", "Bumblebee", "Bundlore", "BUSHWALK", "BusyGasper", "Cachedump", "CaddyWiper", 
    "Cadelspy", "CALENDAR", "Calisto", "CallMe", "Cannon", "Carbanak", "Carberp", "Carbon", 
    "CarbonSteal", "Cardinal RAT", "CARROTBALL", "CARROTBAT", "Catchamas", "Caterpillar WebShell", 
    "CCBkdr", "ccf32", "Cerberus", "certutil", "Chaes", "Chameleon", "Chaos", "Charger", "CharmPower", 
    "ChChes", "Cheerscrypt", "CHEMISTGAMES", "Cherry Picker", "CHIMNEYSWEEP", "China Chopper", "Chinoxy", 
    "CHOPSTICK", "Chrommme", "Circles", "Clambling", "Clop", "CloudDuke", "cmd", "COATHANGER", 
    "Cobalt Strike", "Cobian RAT", "CoinTicker", "Comnie", "ComRAT", "Concipit1248", "Conficker", 
    "ConnectWise", "Conti", "CookieMiner", "CORALDECK", "CORESHELL", "Corona Updates", "CosmicDuke", 
    "CostaBricks", "Covenant", "CozyCar", "CrackMapExec", "CreepyDrive", "CreepySnail", "Crimson", 
    "CrossRAT", "Crutch", "Cryptoistic", "CSPY Downloader", "Cuba", "Cuckoo Stealer", "Cyclops Blink", 
    "Dacls", "DanBot", "DarkComet", "DarkGate", "DarkTortilla", "DarkWatchman", "Daserf", "DCSrv", 
    "DDKONG", "DEADEYE", "DEADWOOD", "DealersChoice", "DEATHRANSOM", "DEFENSOR ID", "Dendroid", "Denis", 
    "Derusbi", "Desert Scorpion", "Diavol", "Dipsind", "Disco", "DnsSystem", "DOGCALL", "Dok", "Doki", 
    "Donut", "DoubleAgent", "down_new", "Downdelph", "DownPaper", "DRATzarus", "DressCode", "Dridex", 
    "Drinik", "DroidJack", "DropBook", "Drovorub", "dsquery", "Dtrack", "DualToy", "Duqu", "DUSTPAN", 
    "DUSTTRAP", "DustySky", "Dvmap", "Dyre", "Ebury", "ECCENTRICBANDWAGON", "Ecipekac", "Egregor", 
    "EKANS", "Elise", "ELMER", "Emissary", "Emotet", "Empire", "EnvyScout", "Epic", "Escobar", 
    "esentutl", "eSurv", "EventBot", "EvilBunny", "EvilGrab", "EVILNUM", "Exaramel for Linux", 
    "Exaramel for Windows", "Exobot", "Exodus", "Expand", "Explosive", "Fakecalls", "FakeM", "FakeSpy", 
    "FALLCHILL", "FatDuke", "Felismus", "FELIXROOT", "Ferocious", "Fgdump", "Final1stspy", "FinFisher", 
    "FIVEHANDS", "Flagpro", "Flame", "FLASHFLOOD", "FlawedAmmyy", "FlawedGrace", "FlexiSpy", "FLIPSIDE", 
    "FlixOnline", "FluBot", "FlyTrap", "FoggyWeb", "Forfiles", "FRAMESTING", "FrameworkPOS", "FrozenCell", 
    "FRP", "FruitFly", "ftp", "FunnyDream", "Fuxnet", "FYAnti", "Fysbis", "Gazer", "Gelsemium", 
    "GeminiDuke", "Get2", "gh0st RAT", "Ginp", "GLASSTOKEN", "GLOOXMAIL",
      "Gold Dragon", "Golden Cup","GoldenEagle", "GoldFinder", "GoldMax",
        "GoldSun", "Gooke", "Google Installer", "GoogleHelper", 
    "GootLoader", "Gorgon", "GraceWire", "GraveSnake", "GravityRAT", "GreedyAnt", "Green Lambert", 
    "GridinSoft", "GrimAgent", "Grixba", "GuLoader", "Guerrilla", "GuLoader", "Gustuff", "GwisinLocker", 
    "H1N1", "Hadoken", "Hafnium", "HALFBAKED", "Halvor", "HAMMERTOSS", "Hand of Thief", "Hansitor", 
    "Hantiff", "HappyTrigger", "HardHead", "HardRain", "HardwareImplant", "Havex", "HazardAvert", 
    "Heelected", "Helminth", "Helux", "HermeticRansom", "HermeticWiper", "Hidden Bee", "Hidden Cobra", 
    "HiddenIFrame", "Higaisa", "Hikit", "Hilow", "HinataBot", "Hitcher", "HJLoader", "Hoaxcalls", 
    "Hodur", "Holy Water", "Hook Malware", "HookInj3ct0r", "Hooker", "HopLight", "HotCroissant", 
    "HotSniper", "HotWind", "House of Keys", "HpSecScan", "Htran", "HttpBrowser", "HummingBad", 
    "HummingWhale", "Hvnc", "HyberBit", "HydraPOS", "HyperBro", "HyperShell", "IcedID", "ICMPBack", 
    "Icefog", "Iconburst", "IDEAFABRIC", "IksMas", "ILOVEYOU", "IMBot", "Imec", "Imminent Monitor", 
    "Implant32", "Implant64", "Inception", "Industroyer", "InfoStealer", "Injector", "InnaputRAT", 
    "InsiderSpy", "InsideWiper", "InstallerSpy", "InterPlanetary RAT", "IOTrooper", "Irontiger", 
    "IronViking", "ISC", "ISHUNT", "ISpy", "IsStaler", "IZ Loader", "JackPOS", "Jackpotting", 
    "Jailbreak", "JangGong", "Javali", "JBossBackdoor", "Joker Malware", "Jokerrat", "Joumal", 
    "Joy Malware", "JoyRAT", "Jucyspay", "Jumpjump", "Jupyter", "Jusby", "Kagent", "Kajack", "Kanger", 
    "Kanji Virus", "Karagany", "Karasu", "Katana", "Kazuar", "KAZURO", "KE3Chang", "KEELOPGUI", "Kelihos", 
    "KeyBoy", "Keyhole", "Keylogger", "KeyloggerX", "Keysniffer", "KGH", "KGH_Loader", "KGH_Spreader", 
    "Khalesi", "Khronos", "Kickass", "KillDisk", "KillNet", "Kimsuky", "Kins", "Kitty Ransomware", 
    "Klepto", "Klipod", "Koadic", "Koobface", "Koobface.A", "Kos", "Kovter", "KPOT", "KRBanker", 
    "Kraken", "KRBanker", "Kronecker", "KRBot", "Kryptic", "Krypton", "Kudun", "Kurt", "KurtSpy", 
    "Kuzar", "KVlogger", "Kwampirs", "Lacrosse", "Ladon", "Lajack", "LameRAT", "Lampion", "Lapsus$", 
    "LastConnection", "Latin", "Lattice", "Lazarus RAT", "LCBLA", "LCPatch", "LDR", "Leapfrog", 
    "LEDBREAK", "LegendStealer", "Leitner", "Lemur", "Leo Virus", "Leviathan", "LfHeader", "LibraRAT", 
    "Lightning", "LIME", "LimeRAT", "Limeworm", "Linas", "Linda", "LineSwapper", "Linkspace", "LinuxPen", 
    "Lion", "Lionheart", "Lipoker", "LittleLoader", "Locebot", "Loda RAT", "LockerGaga", "LockerPin", 
    "LockerX", "Locky", "Lolita", "LolZop", "Loncom", "LoRaScreamer", "Lowkey", "Lpanvirus", "LunarIce", 
    "LunaRAT", "Lurk", "Luwuk", "Lyceum", "Lykos", "Mabutu", "MacCopier", "MachO", "MacRemover", 
    "MadBear", "Madera", "Magenta", "Magneto", "Magniber", "Mahalo", "MajikPOS", "MALBBOT", "MalDoc", 
    "Malibot", "MALNET", "Man-In-Middle", "MantaRay", "Marap", "Mariposa", "Mars Stealer", "Masuta", 
    "Matanbuchus", "Matrix", "Matryoshka", "Maui", "Maverick", "MaxiData", "Maze", "Mbrokernow", 
    "MediStealer", "Medusa", "MedusaLocker", "Megumin", "MelcoRAT", "Meow", "MERLING", "MesaSpy", 
    "MessegerApp", "Metador", "Metamorphic Virus", "MeteorExpress", "Mimikatz", "MiniDuke", "MiniStuk", 
    "Minsk", "Mintegral", "Mirai", "Mishka", "Mistake", "Mistry", "Mivast", "Mizura", "MoBot", "MoMoney", 
    "Moche", "MoChina", "MoleRats", "Molotok", "Mongoz", "Monokle", "MoneroMiner", "Monochrome", 
    "Monster", "Moonbounce", "MoonCity", "MoonLight", "Morpheus", "MosaicRegressor", "Mosquito", 
    "Moudoor", "MouseTrap", "MoveYourBody", "Mozart", "MpMPowerShell",
    "MR Black", "Mr.Dec", "MrGray", "MRTakeOver", "MSBot", "MsnMM", "MuChard", "MuddyWater", 
    "MultiPlug", "MultiStealer", "MurkyTop", "Mushtik", "MuTaRAT", "MuVar", "Muze Loader", 
    "MVT", "Mydas", "MyKings", "Mykings Botnet", "Mystic", "Mythic", "Naikon", "Naski", 
    "Natez", "Nazar", "Nebula", "Necro", "NecroBot", "Necurs", "Nefilim", "Nemesis", 
    "Nemty", "NetKey", "Netbot", "NetCore", "NetDooka", "Netflash", "Netlab", "NetTraveler", 
    "Netwalker", "NetworkEspionage", "Neutrino", "NeverQuest", "Nexus", "NextCry", 
    "Ngrok", "NiceTry", "NightDragon", "NightHawk", "NightSky", "Nimble", "Nimda", 
    "NIR", "Nitol", "NjRat", "Nocturnal", "NodeBot", "Noip", "Nomax", "Nonamed", 
    "Nonex", "Norman", "Normie", "NorthStar", "NotPetya", "NoxPlayer", "NoxSpy", 
    "NSAbot", "NSAToolkit", "NullMixer", "NullTerminator", "NumberZero", "Nurum", 
    "NVF", "Nvram", "NxSpy", "Nymaim", "Oasis", "Oblivion", "Oblivious", "OblivionStealer", 
    "Observer", "Obsidian", "OceanLotus", "OceanSalt", "Octopus", "Odin", "OEKLoader", 
    "OfficeScan", "OgrO", "OhMyGod", "OilRig", "Oktopus", "Olive", "Omega", "Omni", 
    "OmniBot", "Omnicore", "Onliner", "OODA", "OpFake", "Opium", "Opportunist", "Optimus", 
    "Orcus", "Orderly", "Ordinypt", "Orion", "Orlangur", "Ornate", "Orzuz", "OSStealer", 
    "Ostrich", "OTAPayload", "Outlaw", "OutlookStealer", "OvBot", "OverLoader", 
    "OverWatch", "OxyBot", "P2Loader", "P2PCapture", "PandaBanker", "PandaStealer", 
    "Panther", "PaperLoader", "Paradise", "Parallax", "Paranoid", "Parrot", "Patchwork", 
    "Pay2Cry", "PayDay", "PaySafe", "Payloadbot", "PayToKey", "Peach", "Peacock", 
    "Peeling", "Peppy", "Perch", "Perseus", "Petya", "Pezi", "Phantom", "Phobos", 
    "PhonyC", "Phorpiex", "Photon", "Phrozen", "Phrozensoft", "PHPExploiter", "Picasso", 
    "PickleRAT", "Piercer", "Piggy", "PigLoad", "PigTails", "Pinchy", "Pingback", 
    "PinkSlime", "Pinpoint", "PipeMon", "Pipeline", "PipeRAT", "Pixie", "Pixelate", 
    "Pixload", "Plague", "Planet", "Plasma", "PlatBot", "Platinum", "PlayerZero", 
    "PLEAD", "PlugBot", "PlugX", "Plunder", "Plutus", "PMWizard", "Poco", "PoisonIvy", 
    "Polaris", "Polonium", "Pony", "Popcorn", "PopRAT", "Porcelain", "Portal", 
    "Poster", "PostPixel", "PowerLoader", "PowerSploit", "PowerTrick", "PowerWare", 
    "PowerWorm", "PowerZeus", "PPStealer", "Praetorian", "PrayingMantis", "Predator", 
    "PredatorTheThief", "Premier", "PrimeBot", "PrinceOfPersia", "Princeton", "Procyon", 
    "ProcSnap", "ProDigger", "Programmatic", "ProjectCrow", "ProjectVenom", "Prometheus", 
    "Prometei", "Prophet", "Proton", "ProtonBot", "Prowler", "ProxyBack", "ProxyLoader", 
    "Psylo", "PsyloStealer", "Pterosaur", "Pulsar", "PulseBot", "Punisher", "Pupy", 
    "PurpleFox", "PyCrypto", "PyInstaller", "PyRat", "PyXie", "PyZer", "QakBot", 
    "Qarallax", "QasBot", "Qbot", "Quasar", "QuasarRAT", "Quantum", "QueegBot", 
    "QueueTask", "QuickHeal", "QuickLocker", "QuickSilver", "QuiltBot", "R4Shell", 
    "Raccoon", "RaccoonStealer", "RagnarLocker", "RaiLoader", "Rainbot", "Rainbow", 
    "Ramsay", "Ramson", "Ranser", "RansomEXX", "RansomHero", "RansomLocker", "RansomPlus", 
    "RansomStar", "RansomSteal", "RansomTool", "Rapid", "Rarog", "Ratankba", "RavenClaw",   
    "RavenStorm", "RawPOS", "RayBan", "Razor", "Razzy", "RcBot", "RCSession", "RCSploit", 
    "RDPStealer", "RDPThief", "RDPTool", "Reaper", "RebuildBot", "Recon", "ReconCat", 
    "ReconSploit", "Recover", "RectLoader", "RedAlert", "RedCarpet", "RedEcho", 
    "RedEnergy", "RedEye", "RedFox", "RedKit", "RedLeaves", "RedLine", "RedMoon", 
    "RedOctober", "RedRat", "RedStinger", "RedX", "ReegSpy", "ReelSpy", "Refactor", 
    "Refraction", "Refrain", "RegBot", "Regin", "RegretLoader", "Relay", "RemoteBolt", 
    "RemoteHook", "RemoteJoy", "RemoteSpy", "RemoteTool", "RemoteWizard", "Remy", 
    "Renaissance", "Renoir", "Reptile", "ReqBot", "Resin", "Resolution", "Resurrector", 
    "Retaliator", "RetroBot", "RetroKit", "RetroSploit", "Revel", "RevLoader", 
    "Revolution", "ReWorm", "Rex", "RexBot", "RexStealer", "ReyBot", "ReyLoader", 
    "RFSpy", "Rhino", "RhinoBot", "RhinoStealer", "Ribbon", "RichHound", "Rifle", 
    "RigEK", "Rime", "RingBot", "RingLoader", "RingZero", "RipBot", "RipLoader", 
    "Ripper", "RisingSun", "Ritalin", "Rival", "Rizal", "RLoad", "RoamingRat", 
    "RoamingSpy", "RoadHouse", "RoamingTool", "Robber", "RoboBot", "RoboLoader", 
    "Robotnik", "RoboWorm", "Rogue", "RogueAccess", "RogueKit", "RogueSploit", 
    "RogueWizard", "RollingBot", "RollingLoader", "RollingStone", "Romance", 
    "Rook", "RoomBack", "RootAccess", "RootBot", "RootDigger", "RootLoader", 
    "RootSploit", "RootWorm", "RopBot", "RopLoader", "RopeMaster", "RopeSploit", 
    "RopeWizard", "Rosa", "RoseBot", "RoseLoader", "RosePetal", "RoseSploit", 
    "RoseWizard", "Rover", "Royal", "RoyalLoader", "RoyalSploit", "Royalty", 
    "Rubicon", "Rubik", "Ruckus", "Rudra", "Rugrat", "Ruins", "Rumor", "Runaway", 
    "RunBot", "RunLoader", "RunSploit", "RunWizard", "Runner", "RustBucket", 
    "Rusty", "Ruthless", "RVLoader", "RwarBot", "RWarrior", "RXBot", "RxLoader", 
    "RxStealer", "Saber", "Sabotage", "Sable", "Sacrifice", "Saddle", "SafeLoad", 
    "Safeguard", "Sage", "SageLoader", "SageWizard", "Saint", "Salamander", 
    "Salmon", "Salvage", "Samurai", "SandCat", "SandFly", "SandMan", "SandWorm", 
    "Sangoma", "Sapphire", "SaphireBot", "Sapient", "Satchel", "Satellite", 
    "Saturn", "Savage", "Sawtooth", "Sawyer", "ScabBot", "Scalpel", "Scammer", 
    "Scarlet", "Scary", "Scatter", "ScatterLoader", "ScatterWizard", "Scenario", 
    "Scenic", "Scimitar", "Scissors", "Scooter", "Score", "Scout", "Scrapper", 
    "Scratcher", "Screamer", "ScreenSpy", "ScreenTool", "ScreenWizard", "Scribe", 
    "Scrutinizer", "Scurvy", "Scythe", "SeaHawk", "SeaHorse", "Seal", "Seaman", 
    "Seashell", "Seaside", "Seeker", "Sentinel", "Sepia", "Seraph", "Serenity", 
    "Sermon", "Serpent", "Serrano", "Servo", "SessionSpy", "SetBot", "SetLoader", 
    "SetSploit", "SetWizard", "Setup", "SevenStars", "Shadow", "ShadowBot", 
    "ShadowSploit", "ShadowWizard", "Shady", "Shaman", "ShanBot", "Sharp", "Shepherd", 
    "Sherlock", "Shield", "Shiny", "Shock", "ShockBot", "ShockLoader", "ShockWizard", 
    "Shooter", "Shortstop", "Showdown", "Shrike", "Shroud", "Shuriken", "Siberia", 
    "Siberian", "Sickle", "SideKick", "Siege", "SiegeBot", "SiegeLoader", "Sierra", 
    "Silent", "SilentBot", "SilentSploit", "SilentWizard", "Silhouette", "SilkRoad", 
    "Silky", "SilverFox", "SilverLight", "SilverSnake", "Simmer", "SimpleBot", 
    "SimpleLoader", "SimpleSploit", "SimpleWizard", "Simulacrum", "Sinatra", "SineWave", 
    "Sinister", "Sinistral", "Sinkhole", "SirBot", "SirLoader", "SirSploit", "SirWizard", 
    "Siren", "SiteHunter", "Sixfold", "SixShooter", "Skater", "Skeleton", "SkeletonKey", 
    "Skipper", "Skorpion", "Skunk", "SkyBot", "Skyline", "SkyRider", "SkyWizard", 
    "SkyWolf", "Slash", "Slasher", "Slayer", "Sleepy", "Slice", "Slider", "Slingshot", 
    "SlipStream", "Slither", "Slug", "Slumber", "Sly", "SmallBot", "SmallLoader", 
    "SmallSploit", "SmallWizard", "SmashBot", "SmashLoader", "SmashSploit", "SmashWizard", 
    "Smith", "Smoke", "SmokeBot", "SmokeLoader", "SmokeSploit", "SmokeWizard", 
    "Smuggler", "Snap", "SnapDragon", "Snapper", "Snare", "Sneaker", "Sneaky", 
    "Snitch", "Snorlax", "Snow", "SnowBot", "SnowLoader", "SnowSploit", "SnowWizard", 
    "Soar", "Sobek", "Socket", "SoftLoader", "SoftSploit", "SoftWizard", "Soggy", 
    "Solar", "SolarBot", "SolarLoader", "SolarSploit", "SolarWizard", "Solstice", 
    "Solution", "Somber", "Sombra", "Sonar", "Sonic", "SonicBoom", "SonicBot", 
    "SonicLoader", "SonicSploit", "SonicWizard", "Sorcery", "Sorcerer", "Sorrow", 
    "Soul", "SoulBot", "SoulLoader", "SoulSploit", "SoulWizard", "Source", "Sovereign", 
    "SovereignBot", "SovereignLoader", "SovereignSploit", "SovereignWizard", 
    "Spark", "SparkBot", "SparkLoader", "SparkSploit", "SparkWizard", "Sparrow", 
    "Spawn", "SpawnBot", "SpawnLoader", "SpawnSploit", "SpawnWizard", "Specter", 
    "SpecterBot", "SpecterLoader", "SpecterSploit", "SpecterWizard", "Spectrum", 
    "SpeedBot", "SpeedLoader", "SpeedSploit", "SpeedWizard", "Spell", "SpellBot", 
    "SpellLoader", "SpellSploit", "SpellWizard", "Sphere", "SphereBot", "SphereLoader", 
    "SphereSploit", "SphereWizard",    "Spike", "SpikeBot", "SpikeLoader",
      "SpikeSploit", "SpikeWizard", "Spinner", 
    "Spiral", "Spirit", "SpiritBot", "SpiritLoader", "SpiritSploit", "SpiritWizard", 
    "Splash", "SplashBot", "SplashLoader", "SplashSploit", "SplashWizard", "Splinter", 
    "SplinterBot", "SplinterLoader", "SplinterSploit", "SplinterWizard", "Splurge", 
    "Spoiler", "Sponge", "Spoon", "Spotlight", "Spray", "SprayBot", "SprayLoader", 
    "SpraySploit", "SprayWizard", "Sprinter", "Sprite", "Spur", "SpyBot", "Spyder", 
    "SpyGlass", "SpyLoader", "SpySploit", "SpyWizard", "Squad", "Square", "Squash", 
    "Squid", "Squirt", "Squirrel", "Stag", "Stalker", "Stampede", "Standard", 
    "StarBot", "StarDust", "StarGazer", "StarLight", "StarLoader", "StarSploit", 
    "StarWizard", "Stark", "Static", "StaticBot", "StaticLoader", "StaticSploit", 
    "StaticWizard", "Statue", "Stealth", "StealthBot", "StealthLoader", "StealthSploit", 
    "StealthWizard", "Steel", "SteelBot", "SteelLoader", "SteelSploit", "SteelWizard", 
    "Stencil", "StepBot", "StepLoader", "StepSploit", "StepWizard", "Stereo", 
    "Sterling", "Stiletto", "Stinger", "StingRay", "Stone", "StoneBot", "StoneLoader", 
    "StoneSploit", "StoneWizard", "Storm", "StormBot", "StormLoader", "StormSploit", 
    "StormWizard", "Stratus", "Stray", "Stream", "StreamBot", "StreamLoader", 
    "StreamSploit", "StreamWizard", "Strength", "Striker", "Strix", "Strobe", 
    "Stronghold", "Stubborn", "Stubby", "Studio", "Stumble", "StunBot", "StunLoader", 
    "StunSploit", "StunWizard", "Styx", "SubBot", "SubLoader", "SubSploit", "SubWizard", 
    "Submarine", "Submerge", "Submit", "Subtle", "SubtleBot", "SubtleLoader", 
    "SubtleSploit", "SubtleWizard", "Success", "Sucker", "Sudden", "Sugar", 
    "Sulfur", "SulfurBot", "SulfurLoader", "SulfurSploit", "SulfurWizard", "Summer", 
    "SunBot", "Sunburst", "SunLoader", "Sunrise", "Sunset", "Sunshine", "Super", 
    "SuperBot", "SuperLoader", "SuperSploit", "SuperWizard", "Superior", "Surge", 
    "SurgeBot", "SurgeLoader", "SurgeSploit", "SurgeWizard", "Surprise", "Sushi", 
    "Swamp", "Swarm", "SwarmBot", "SwarmLoader", "SwarmSploit", "SwarmWizard", 
    "Sweep", "SweepBot", "SweepLoader", "SweepSploit", "SweepWizard", "Sweet", 
    "Swift", "SwiftBot", "SwiftLoader", "SwiftSploit", "SwiftWizard", "Sword", 
    "SwordBot", "SwordLoader", "SwordSploit", "SwordWizard", "Syndicate", "Synergy", 
    "Syntax", "Syringe", "System", "SystemBot", "SystemLoader", "SystemSploit", 
    "SystemWizard", "Taboo", "Tackle", "Tactical", "Tactician", "Tails", "Talon", 
    "Tanker", "Tanky", "Target", "Tarnish", "Taser", "Tasker", "Tattle", "Tattoo", 
    "Taunt", "Taurus", "Tavern", "Tectonic", "Teddy", "Teeth", "Temper", "Tempest", 
    "Templar", "Temple", "Temporal", "Tenacity", "Tenet", "Tengu", "Tender", 
    "Tension", "Terminator", "Terrain", "Terrier", "Terror", "TerrorBot", 
    "TerrorLoader", "TerrorSploit", "TerrorWizard", "Tesla", "TeslaBot", 
    "TeslaLoader", "TeslaSploit", "TeslaWizard", "TestBot", "TestLoader", 
    "TestSploit", "TestWizard", "Thane", "Thankful", "Thanos", "Theater", 
    "Theory", "Thermal", "Thief", "ThiefBot", "ThiefLoader", "ThiefSploit", 
    "ThiefWizard", "Thing", "Thorn", "ThorBot", "Thrash", "Thread", "Threshold", 
    "Thresher", "Thunder", "ThunderBot", "ThunderLoader", "ThunderSploit", 
    "ThunderWizard", "Thyme", "TickBot", "Ticker", "TickTock", "Tiger", 
    "TigerBot", "TigerLoader", "TigerSploit", "TigerWizard", "Tight", "Tightrope", 
    "Tinker", "TinkerBot", "TinkerLoader", "TinkerSploit", "TinkerWizard", 
    "Tinsel", "Titan", "TitanBot", "TitanLoader", "TitanSploit", "TitanWizard", 
    "Tombstone", "Topaz", "Torch", "TorchBot", "TorchLoader", "TorchSploit", 
    "TorchWizard", "Torrent", "Torpedo", "Torque", "Tornado", "TorpBot", 
    "TorpLoader", "TorpSploit", "TorpWizard", "Tough", "Toxic", "Tracer", 
    "Tracker", "Trade", "Trader", "Trail", "TrailBot", "TrailLoader", 
    "TrailSploit", "TrailWizard", "Train", "Trainer", "TramBot", "TramLoader", 
    "TramSploit", "TramWizard", "Transform", "Transformer", "Trap", "Traveler", 
    "Treasure", "TreeBot", "TreeLoader", "TreeSploit", "TreeWizard", "Tremor", 
    "Trend", "Trendy", "Trepid", "Triad", "Triangle", "Trident", "Trigger", 
    "Trinity", "Triple", "Troll", "TrollBot", "TrollLoader", "TrollSploit", 
    "TrollWizard", "Trophy", "Trojan", "TrojanBot", "TrojanLoader", "TrojanSploit", 
    "TrojanWizard", "Tropic", "Trouble", "TroubleBot", "TroubleLoader", 
    "TroubleSploit", "TroubleWizard",    "Truce", "Truck", "True", "Trump",
      "Trust", "Tsunami", "Tumbler", "Tundra", 
    "Tunnel", "Turbo", "Turbot", "Turmoil", "Turtle", "Twilight", "Twin", 
    "Twinkle", "Twist", "Twitch", "Tycoon", "Typhoon", "UFO", "Umbra", "Unicorn", 
    "Union", "Unique", "Unit", "Unity", "Universe", "Unknown", "Update", "Upset", 
    "Uprising", "Urban", "Urchin", "Utility", "Utopia", "Vacuum", "Valkyrie", 
    "Valor", "Vampire", "Vanilla", "Vapor", "Vector", "Vega", "Velocity", 
    "Venom", "Venture", "Verge", "Vermin", "Vertex", "Vesper", "Vibe", "Victor", 
    "Victory", "Vigil", "Viking", "Viper", "Virtue", "Vision", "Void", "Volt", 
    "Voltage", "Vortex", "Voyager", "Vulcan", "Vulture", "Waffle", "Warden", 
    "Warlock", "Warp", "Warrior", "Watchdog", "Waterfall", "Wave", "Weaver", 
    "Web", "Whale", "Whisper", "Whistle", "White", "Wicked", "Wild", "Willow", 
    "Wind", "Wing", "Winter", "Wisdom", "Wisp", "Wizard", "Wolf", "Wonder", 
    "Wraith", "Wrangler", "Wrath", "Wrench", "Wrestler", "Wriggle", "Wyvern", 
    "XBot", "XCalibur", "XFactor", "Xplorer", "XRay", "XRider", "XStream", 
    "Xtreme", "Xylophone", "Yak", "Yamato", "Yankee", "Yardstick", "Yarn", 
    "Yellow", "Yield", "Yonder", "Young", "Youth", "Yucca", "Yukon", "Zag", 
    "Zebra", "Zenith", "Zero", "Zeus", "Zigzag", "Zinc", "Zodiac", "Zombie", 
    "Zone", "Zoom", "Zorro", "Zuma", "Zydeco"
]
    for malware in known_malware:
        if malware.lower() in text.lower():
            malware_details.append({'Name': malware, 'md5': 'sample_md5_hash'})
    return malware_details

# Define function to extract targeted entities
def extract_targeted_entities(text):
    targeted_entities = []
    # Example sectors (expand this list)
    known_sectors = ["Energy Sector", "Healthcare", "Finance","Financial Services",
    "Healthcare and Pharmaceuticals",
    "Energy and Utilities",
    "Information Technology",
    "Telecommunications",
    "Government and Military",
    "Education",
    "Retail and E-commerce",
    "Manufacturing",
    "Transportation and Logistics",
    "Media and Entertainment",
    "Real Estate and Construction",
    "Aerospace and Defense",
    "Hospitality and Travel",
    "Legal Services",
    "Non-Profit Organizations",
    "Insurance",
    "Agriculture and Food Supply",
    "Chemical Industry",
    "Mining and Natural Resources",
    "Professional Services",
    "Automotive Industry",
    "Electronics and Semiconductors",
    "Research and Development",
    "Supply Chain and Warehousing",
    "Maritime and Shipping",
    "Nuclear Facilities",
    "Water Treatment and Distribution",
    "Postal and Courier Services",
    "Emergency Services",
    "Space and Satellite Communications",
    "Religious Institutions","Small and Medium Enterprises (SMEs)",
    "Cryptocurrency and Blockchain",
    "Election Systems and Voting Infrastructure",
    "Cloud Service Providers",
    "Social Media Platforms",
    "Digital Marketing and Advertising",
    "Public Utilities",
    "Internet Service Providers (ISPs)",
    "Biotechnology and Life Sciences",
    "Online Gaming and Gambling",
    "Entertainment Streaming Platforms",
    "Shipping and Ports",
    "Humanitarian Organizations",
    "Food and Beverage Industry",
    "Textile and Apparel",
    "Environmental Organizations",
    "Defense Contractors",
    "Cybersecurity Firms",
    "Academic Research Institutions",
    "Hardware Manufacturers",
    "Satellite Technology Providers",
    "Oil and Gas Industry",
    "Online Payment Processors",
    "Public Transit Systems",
    "News and Journalism Organizations",
    "Sports Organizations",
    "International Organizations )",
    "Public Health Organizations",
    "Virtual Reality (VR) and Augmented Reality (AR) Technology Providers",
    "Fitness and Health Apps",
    "Drone Manufacturing and Operation"]
    for sector in known_sectors:
        if sector.lower() in text.lower():
            targeted_entities.append(sector)
    return targeted_entities

# Main pipeline function
def extract_threat_intelligence(report_text):
    result = {}
    
    # Extract IoCs
    result['IoCs'] = extract_iocs(report_text)
    
    # Extract TTPs
    result['TTPs'] = extract_ttps(report_text)
    
    # Extract Threat Actors
    result['Threat Actor(s)'] = extract_threat_actors(report_text)
    
    # Extract Malware details
    result['Malware'] = extract_malware(report_text)
    
    # Extract Targeted Entities
    result['Targeted Entities'] = extract_targeted_entities(report_text)
    
    return result

# Example report text

import PyPDF2
import pytesseract
from pdf2image import convert_from_path
from PIL import Image
import io

def extract_text_from_pdf(pdf_path):
    try:
        # Open the PDF file in read-binary mode
        with open(pdf_path, 'rb') as pdf_file:
            # Create a PDF reader object
            reader = PyPDF2.PdfReader(pdf_file)
            
            # Initialize a string to store the extracted text
            extracted_text = ""

            # Extract text from each page
            for page_num, page in enumerate(reader.pages):
                # Extract text from the page
                text = page.extract_text()
                if text:
                    extracted_text += f"Text from page {page_num + 1}:\n{text}\n"
                
                # If no text is found, we will extract text from images using OCR
                else:
                    extracted_text += f"Text from images on page {page_num + 1}:\n"
                    # Convert PDF page to image
                    images = convert_from_path(pdf_path, first_page=page_num+1, last_page=page_num+1)
                    for image in images:
                        # Use pytesseract to extract text from image
                        ocr_text = pytesseract.image_to_string(image)
                        extracted_text += ocr_text + "\n"

        return extracted_text

    except Exception as e:
        return f"An error occurred: {e}"

# Example usage
pdf_path =input ("Enter the pdf file path :-- ")  # Replace with your PDF file path
report_text = extract_text_from_pdf(pdf_path)


# Run the pipeline
result = extract_threat_intelligence(report_text)
print(result)